config/routes.rb
Rails.application.routes.draw do
  resources :products do
    resources :comments
  end
  mount ActionCable.server => '/cable'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :users 

  resources :orders, only: [:index, :show, :create, :destroy]
  
  get 'static_pages/about'

  get 'static_pages/contact' 

  get 'static_pages/index'

  post 'static_pages/thank_you'

  post 'payments/create'

  root 'static_pages#landing_page'

end

app/views/layouts/_navbar.html.erb
 
  <nav class="navbar navbar-inverse">
    <div class='container'>
      <div class='navbar-header'>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
        <ul class="nav navbar-nav">
          <li class='active'><%= link_to "Home", root_url %></li>
          <li><%= link_to "About", static_pages_about_path %></li>
          <li><%= link_to "Contact", static_pages_contact_path %></li>
          <li><%= link_to "Products", products_path %></li>
          <li>
            <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            <% else %>
              <%= link_to('Login', new_user_session_path) %>
            <% end %>
          </li>
        </ul>
        <ul class='nav navbar-nav navbar-right'>  
          <li>
            <%= form_tag products_path, :method => "GET" do %>
              <%= label_tag(:q) %>
              <%= text_field_tag(:q) %>
              <%= submit_tag("Search", class: 'btn btn-default') %>
            <% end %>    
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/_notices.html.erb
  <div class="notice">
    <% if notice %>
      <p id="notice" class="alert alert-info" button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"></span></button>
      <strong><%= notice %></strong></p>
    <% end %>
  </div>
  <div class="alert">
    <% if alert %>
      <p id="alert" class="alert alert-info" button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"></span></button>
      <strong><%= alert %></strong></p> <!-- these are buttons to close the alert -->
    <% end %>
  </div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang='en'>
  <head>
    <title>ARC Sports Tech</title>

    <%= csrf_meta_tags %>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>

    <%= render 'layouts/navbar' %>

    <%= render 'layouts/notices' %>

    <div class='container'>
      <%= yield %>
    </div>

    <footer class="footer">
      &copy; 2017 Arc Sports Tech
    </footer>

  </body>
</html>